# Generated by Django 5.1.6 on 2025-02-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='header/')),
                ('catchphrase', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Background',
        ),
    ]
